export const vocab = [
    { word: "Apple", translation: "Syaau" },
    { word: "Banana", translation: "Kera" },
    { word: "Grape", translation: "Angur" },
    { word: "Guava", translation: "Amba" },    
    { word: "Water", translation: "Pani" },
    { word: "Cat", translation: "Biralo" },
    { word: "Dog", translation: "Kukur" },
    { word: "Horse", translation: "Ghoda" },
    { word: "House", translation: "Ghar" },
    { word: "Book", translation: "Kitab" },
    { word: "Car", translation: "Gaadi" },
    { word: "Tree", translation: "Rukh" },
    { word: "Sun", translation: "Surya" },
    { word: "Star", translation: "Tara" },
    { word: "Friend", translation: "Sathi" },
    { word: "Family", translation: "Pariwar" },
    { word: "Food", translation: "Khana" },
    { word: "Red", translation: "Rato" },
    { word: "Blue", translation: "Nilo" },
    { word: "Green", translation: "Hariyo" },
    { word: "Yellow", translation: "Pahelo" },
    { word: "Happy", translation: "Khusi" },
    { word: "Sad", translation: "Dukhi" },
    { word: "Money", translation: "Paisa" },
    { word: "Fire", translation: "Aago" },
    { word: "Thank you", translation: "Dhanyabaad" },
    { word: "You", translation: "Timi" },
    { word: "Donkey", translation: "Gadha" },
    { word: "Elephant", translation: "Hatti" },
    { word: "Tiger", translation: "Bagh" },
    { word: "Mouse", translation: "Musa" },
    { word: "Sky", translation: "Aakash" },
    { word: "Cloud", translation: "Badal" },
    { word: "Door", translation: "Dhoka" },
    { word: "Window", translation: "Jhyaal" },
    { word: "Chair", translation: "Kursi" },
    { word: "Socks", translation: "Moja" },
]


