export const vocab = [
    { word: "Apple", translation: "Syaau" },
    { word: "Banana", translation: "Kera" },
    { word: "Grape", translation: "Angur" },
    { word: "Guava", translation: "Amba" },    
    { word: "Water", translation: "Pani" },
    { word: "Cat", translation: "Biralo" },
    { word: "Dog", translation: "Kukur" },
    { word: "House", translation: "Ghar" },
    { word: "Book", translation: "Kitab" },
    { word: "Car", translation: "Gaadi" },
    { word: "Tree", translation: "Rukh" },
    { word: "Sun", translation: "Surya" },
    { word: "Star", translation: "Tara" },
    { word: "Friend", translation: "Sathi" },
    { word: "Family", translation: "Pariwar" },
    { word: "Food", translation: "Khana" },
    { word: "Red", translation: "Raato" },
    { word: "Blue", translation: "Nilo" },
    { word: "Green", translation: "Hariyo" },
    { word: "Happy", translation: "Khusi" },
    { word: "Sad", translation: "Dukhi" },
    { word: "Thank you", translation: "Dhanyabaad" },
]


